Upload archives to a product
nerves-hub/nerves_hub_web pull request #1088
Opened 2023-10-30 20:25 UTC by oestrich

Archives are extra firmware files that the device will be told about on connection. This can hold extra data that can be updated out of band from the main firmware.

This also includes a more generic style of uploading that we can convert the previous firmware uploads to in a separate PR. We would need to copy paste the uploader anyways so I went with a style I'm more comfortable with and have used in the past.

2023-11-15 20:02 UTC, jjcarstens requested changes

2023-11-15 20:02 UTC, jjcarstens commented on lib/nerves_hub_web/controllers/archive_controller.ex
Should we also have tests for the controller?

2023-11-16 19:10 UTC, oestrich commented on lib/nerves_hub_web/controllers/archive_controller.ex
> +        if Accounts.has_org_role?(archive.product.org, user, :read) do
Hmm, thinking on this we might still want this check and I'll get rid of the plugs. You could be on the org but pass in another UUID and load it. I'd really like to start de-nesting these routes so I'd prefer to stick with this on further thought

2023-11-16 19:29 UTC, oestrich commented on lib/nerves_hub/archives/archive.ex
> +      # :size,
Oops, we do now

2023-11-20 15:39 UTC, jjcarstens approved these changes

2023-11-20 20:19 UTC, merged