Assign an archive to a deployment
nerves-hub/nerves_hub_web pull request #1091
Opened 2023-11-03 16:26 UTC by oestrich

And send a socket message on device connect to tell about the archive.

2023-11-15 20:13 UTC, jjcarstens requested changes

2023-11-15 20:13 UTC, jjcarstens commented on lib/nerves_hub_web/views/deployment_view.ex
> +    "#{a.version} #{a.platform} #{a.architecture} #{a.uuid}"
```suggestion
    "#{a.version} #{a.uuid} #{a.platform} #{a.architecture}"
```

I feel like version and UUID are probably the most important here. Not sure if we even need the rest, but at least have those 2 together and leftmost

2023-11-15 20:13 UTC, jjcarstens commented on lib/nerves_hub_web/templates/deployment/edit.html.heex
> +    <label for="firmware_id" class="tooltip-label">
```suggestion
    <label for="archive_id" class="tooltip-label">
```

2023-11-16 19:05 UTC, oestrich commented on lib/nerves_hub_web/views/deployment_view.ex
> +    "#{a.version} #{a.platform} #{a.architecture} #{a.uuid}"
This was a copy paste from firmware, so we might want to update that one in another PR

2023-11-20 20:49 UTC, jjcarstens commented on lib/nerves_hub/devices/device_link.ex
> +      :transport_version,
Why `transport_version` vs `device_api_version`? Seems like it might be better to match so it's less confusing?

2023-11-20 20:49 UTC, jjcarstens commented on test/nerves_hub_web/channels/websocket_test.exs
> +      SocketClient.join(socket, "device", %{"device_api_version" => "2.0.0"})
Should we revert all these `device_api_version` checks for now? Its probably better that is the default, but I think we'll want to also have tests for <= 1.0.0 for backwards compatibility

2023-11-20 20:51 UTC, oestrich commented on test/nerves_hub_web/channels/websocket_test.exs
> +      SocketClient.join(socket, "device", %{"device_api_version" => "2.0.0"})
Yeah, that works for me

2023-11-20 20:52 UTC, oestrich commented on lib/nerves_hub/devices/device_link.ex
> +      :transport_version,
I think I just picked it since there were other transport keys, so I'm not sold on it at all. I'll swap them to match

2023-11-20 21:17 UTC, jjcarstens reviewed
Sorry, I forgot one more thing. Can we also get a test in device link for the archive push?

2023-12-12 18:38 UTC, jjcarstens approved these changes

2023-12-12 21:39 UTC, merged