Invites to join an Org require the user to accept the invite
nerves-hub/nerves_hub_web pull request #1346
Opened 2024-06-23 14:56 UTC by beltranaceves

Addressing #1337.

Hi, first time contributing to this repo. I wanted to validate the changes and style before writing tests.

Checklist:
1. [x] When inviting existing users, they are not automatically added to the org until they accept the invite. 
2. [x] Invites for existing users cannot be accepted if the user is not logged in.
3. [x] Invites for existing users cannot be accepted if the logged in user is not the recipient.
4. [x] Invites for new users cannot be accepted if a user is logged in.
5. [ ] Cleaned up temp changes.
6. [ ] Broken test are fixed.
7. [ ] New test have been writen.

2024-06-23 15:10 UTC, beltranaceves commented
I was tempted to add a route for logged in users that lists pending received invites, accessible from the user dropdown menu. But it seems that issues and PRs are fairly atomic, so I kept it pretty barebones

2024-06-23 22:48 UTC, joshk requested changes
Thanks for jumping into this issue! Its great to have new people onboard.

You are on the right track. I have a few suggestions which should clear up the UX of the feature:
- My suggestion would be to have a new banner in the Orgs list (`/`) with a message like "You have x pending invites to Organizations". 
- When you click the message, or link by the message ("View pending invites"), you would then be taken to a page which lists all pending invites. 
- This list would include the Organization name, who invited you (I have this in another PR which I'm just finishing), when they invited you, and two buttons, accept and decline.

Let me know if there is anything I can help with.

2024-06-23 22:48 UTC, joshk commented on lib/nerves_hub/accounts.ex
> +        # add_org_user(org, user, %{role: params["role"]})
I guess this can be simplified to always invite, and not having to search for the user

2024-06-23 22:48 UTC, joshk commented on lib/nerves_hub_web/router.ex
> +    post("/invite_existing/:token", AccountController, :accept_invite_existing)
this should all be possible without another route.

2026-09-07 00:49 UTC, joshk commented
Hi @beltranaceves, thanks for your initial work on this PR. I'm going to close it as it's become stale.

2026-09-07 00:49 UTC, closed without merging