Add dashboard with devices marked on world map
nerves-hub/nerves_hub_web pull request #1457
Opened 2024-08-16 08:43 UTC by elinol

Adds a dashboard to project site, with device locations marked on world map.

The dashboard is disabled from menu by default and is enabled with application variable `:enable_dashboard?`

2024-08-16 09:10 UTC, lawik commented
We should add a way to set the setting in runtime.exs via en environment variable as well. Forgot about that.

2024-08-16 09:11 UTC, elinol commented
![image](https://github.com/user-attachments/assets/e486620e-4f52-4bbc-91bc-301bd112833c)

2024-08-16 09:13 UTC, lawik reviewed
Will let Josh and Jon check in. I just need the runtime.exs so we can deploy :D

2024-08-16 09:13 UTC, lawik commented on lib/nerves_hub_web/live/dashboard/index.html.heex
> +<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
We should probably add this to package.json via npm install instead :/ 

This was my quick way of getting started. It should be able to provide both the leaflet.js and the CSS.

We may want to put it outside of app.js and make it like a map.js that we only load on that view?

2024-08-16 09:13 UTC, lawik commented on lib/nerves_hub_web/live/dashboard/index.html.heex
> +<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
Not sure it's necessary at this stage, but later?

2024-08-16 09:13 UTC, lawik commented on mix.exs
> +      {:hpax, "~> 1.0", override: true},
This was some dep acting up, not sure why.

2024-08-16 09:14 UTC, lawik commented
If we want to hold off on merging this while we tweak it, Josh and I could always deploy it from branch to get the demo done. Do need the runtime.exs for that.

2024-08-16 09:27 UTC, elinol commented on lib/nerves_hub_web/live/dashboard/index.html.heex
> +<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
let's do it now!

2024-08-16 11:55 UTC, elinol commented on mix.exs
> +      {:hpax, "~> 1.0", override: true},
Removed in latest commit

2024-08-16 11:55 UTC, elinol commented
Runtime settings and leaflet npm package was added with latest commit

2024-08-16 23:32 UTC, joshk requested changes
I love where this is going, and think this is a great foundation.

I think for a future iteration we could look into using the Mapbox JS lib (https://docs.mapbox.com/mapbox-gl-js/example/cluster/) as we can do useful things like cluster counts when at different zoom levels, as well as offering a satellite view.

We could also pre zoom in based on the bounding box of the map markers, so if you only have a handful of points in an isolated area, we can zoom in. 

One thing before we merge and ship, what does the 'empty state' look like? Can we show a message over the map to guide users on adding their first device. And we might want to show a legend of what red and green dots means.

2024-08-17 05:16 UTC, lawik commented
Leaflet has plugins that do clustering and pretty much everything else. It should be able to do the fit-zoom around the marker layer though I haven't checked. Mapbox seems to require API access to even use their library and I think that's mildly detrimental to using it in an open source project.

There seems to be an open fork: https://github.com/maplibre/maplibre-gl-js

Mapbox us fine for the detail view since we need tile data.

What makes you prefer them? I am open to the idea but not clear on why they'd be generally preferable :)

2024-08-17 05:17 UTC, lawik commented
Good call on legend and empty state of course.

2024-08-20 10:08 UTC, elinol commented
![image](https://github.com/user-attachments/assets/1c3c9097-e5ce-4efd-ac6b-19ab6e5e4760)
![image](https://github.com/user-attachments/assets/597f40eb-f737-4a52-80c1-e8d59e4e5b21)

2024-08-23 00:22 UTC, joshk approved these changes
Looks good to me!

It would be good to add some form of liveview test for this page, even just to check it shows the empty state if there are no devices with location data, and a map with a dot if there are devices with location data.

Also, as a follow up PR, it would be good to add a summary of how many devices are shown on the map, and how many don't have location data.

eg. 50 devices aren't shown on the map as they don't have any location data.

2024-08-23 09:03 UTC, merged