Change devices list to use query params
nerves-hub/nerves_hub_web pull request #1458
Opened 2024-08-16 12:38 UTC by lawik

Filtering and pagination will now be persisted to the query params which also means we get history and linkable filtering.

2024-08-16 12:39 UTC, lawik commented
I was terribly annoyed by how this view worked. So I fixed it :)

There may be some corners I've missed but I think this is the path forward. I didn't spend any effort on generalizing the pattern which we might want to later.

2024-08-16 12:55 UTC, lawik commented
Ach, think I missed `sort`

2024-08-16 14:45 UTC, jjcarstens commented on lib/nerves_hub_web/live/devices/index.ex
> +    }
We do a lot of map rebuilding and custom filtering here and around this file now. We could potentially leverage Ecto to aid in this casting and safe params:

```elixir
defaults = %{
    page_number: 1,
    page_size: 25,
    page_sizes: [25, 50, 100],
    total_pages: 0
  }

types = %{
    page_number: :integer,
    page_size: :integer,
    page_sizes: {:array, :integer},
    total_pages: :integer
  }

# Safely cast, filter non-allowed params, and set defaults
Ecto.Changeset.cast({defaults, types}, params, Map.keys(defaults))
|> Ecto.Changeset.apply_changes()

# Can also be used to only get the changes from the defaults
Ecto.Changeset.cast({defaults, types}, params, Map.keys(defaults)).changes
```

2024-08-16 14:47 UTC, lawik commented on lib/nerves_hub_web/live/devices/index.ex
> +    }
Cool, will look at that because I'm not happy about the map wrangling. But the functionality is sweet :)

2024-08-16 14:48 UTC, jjcarstens commented on lib/nerves_hub_web/live/devices/index.ex
> +    }
O yes, you are going to make a lot of people cry the tears of joy with this 😂

2024-08-16 23:22 UTC, joshk requested changes
This is awesome

If you want to take it one step further you can change from using lots of `handle_event`s for all the filtering and sorting to instead using patch links in the html.

2024-08-16 23:22 UTC, joshk commented on lib/nerves_hub_web/live/devices/index.ex
> +    NervesHubWeb.Router.Helpers.live_path(
can't we use a verified route string for this?

2024-08-17 05:08 UTC, lawik commented on lib/nerves_hub_web/live/devices/index.ex
> +    NervesHubWeb.Router.Helpers.live_path(
I can try. The most important bit here is that we clean out all default values so we don't get a lot of empty query params.

2024-08-21 14:23 UTC, lawik commented
Good suggestions that just slot in and make the darned thing better. Fancy that.

2024-08-21 20:37 UTC, lawik commented
Not tackling patch links right now, though I imagine that'd be rad. Just hit the sort that I had broken again. Think this is good to go.

2024-08-21 23:55 UTC, joshk approved these changes
aaaaaaaamazing!

2024-08-21 23:55 UTC, merged