Queue deployment recalculation
nerves-hub/nerves_hub_web pull request #1476
Opened 2024-08-28 21:25 UTC by oestrich

Create inflight deployment checks to verify a device is still valid or
is now valid for a deployment. These are processed in a single genserver
per deployment per node. This will help prevent database pool contention
since there should only be a single query per device check per node.

Devices are still checked as fast as possible and will continue to look
for more inflight checks without being told of new updates.

Because deployment updates are processed inside a transaction, any
pubsub messages must be delayed until after the transaction is
successful.

Finding the next device to check is performed with a postgres lock
inside of a transaction. This way we only process a device once.

2024-08-29 02:21 UTC, jjcarstens reviewed
Thanks! I need a bit to review this. It seems there are 2 big changes in here and I'm still catching up how they correlate together. It also is very aggressively locking the rate device updates can be checked. Is this something we could have a knob to tweak at runtime in order to increase the flow if needed?

Also, there is a lot of nesting conditions and blocking. It takes a bit to grok through it to understand what exactly is happening

2024-08-29 15:03 UTC, oestrich commented
We purposefully don't want to increase the rate that we check devices to match a deployment though, since that's what was causing issues. There's no reason we couldn't have multiple calculator processes going at the same time on each node other than running into ecto pooling issues so I've left it at a single per node

2024-09-05 02:33 UTC, fhunleth commented on lib/nerves_hub_web/channels/device_channel.ex
> +  # TODO bring back manually pushed
Just catching up here. I assume the plan is to add manually pushed updates back in this PR, right?

2024-09-05 02:42 UTC, fhunleth requested changes
Marking as "request changes" until the question about manual firmware updates gets resolved.

2024-09-05 02:55 UTC, oestrich commented on lib/nerves_hub_web/channels/device_channel.ex
> +  # TODO bring back manually pushed
![](https://media1.tenor.com/m/-KdqIremkc8AAAAC/andy-chris-pratt.gif)

2024-09-09 19:05 UTC, jjcarstens reviewed
One quick piece to consider. 

There have been a few side discussions around this that I've failed to keep up with and communicate back and forth. There are some concerns and unknowns I keep circle around with this and the complexity it brings, but I also am not being useful in identifying ways around it.

What I've suggested is to allow this to progress as a new calculation path without affecting the old one to allow us to experiment with the SmartRent scale, but have an escape hatch should the unforeseen be worse than the old way this is replacing. That should also give us more path for experimentation and adaptation.

2024-09-10 14:04 UTC, oestrich commented on lib/nerves_hub/deployments.ex
> +            if Enum.any?([:conditions, :is_active], &Map.has_key?(changeset.changes, &1)) do
No? Changing the firmware shouldn't cause a recalculation of the deployment for a device. It will just get the new firmware whenever the orchestrator decides to push it out

2024-09-10 18:56 UTC, jjcarstens commented on lib/nerves_hub/deployments.ex
> +            if Enum.any?([:conditions, :is_active], &Map.has_key?(changeset.changes, &1)) do
Ah yes, I get it now. This is just for recalculation checks, not what firmware to actually get 👍🏼

2024-09-11 17:45 UTC, jjcarstens reviewed
Thanks! A couple comments about testing.

This will work if we really want to move it forward. However, it's still very intermixed and a little hard to follow in the `update_deployment` function. I suggest clearly separating the code paths into functions and not mixing the two, including the topic and event names. Even if there is some code duplication, I think it will make it easier to adjust and review in the future going forward without having to keep so much context in mind and potentially affecting both routes.

What do you think?

2024-09-11 17:45 UTC, jjcarstens commented on priv/repo/migrations/20240910194615_add_recalculation_type_to_deployments.exs
> +      add(:recalculation_type, :recalculation_type, default: "broadcast", null: false)
```suggestion
      add(:recalculation_type, :text, default: "broadcast", null: false)
```
I think we can keep this simple as a text field so we don't have to deal with the woes of enum columns in postgres. We're not really going to need the benefits of enum column since it's a few records and we're not search for the field. We can still use the `Ecto.Enum` type in the schema to get nice atoms and controlling a bit of what gets saved in there.

What do you think?

2024-09-11 17:45 UTC, jjcarstens commented on test/nerves_hub/deployments_test.exs
> -    test "changing tags resets device's deployments and causes a recalculation", state do
Should we leave this test in place for the `broadcast` recalculation?

2024-09-11 17:45 UTC, jjcarstens commented on test/nerves_hub_web/channels/websocket_test.exs
> -    test "assigned a deployment", %{user: user, tmp_dir: tmp_dir} do
Same here?

2024-09-11 18:00 UTC, oestrich commented on priv/repo/migrations/20240910194615_add_recalculation_type_to_deployments.exs
> +      add(:recalculation_type, :recalculation_type, default: "broadcast", null: false)
Works for me, you mentioned enum yesterday so I went that path haha.

2024-09-11 18:03 UTC, jjcarstens commented on priv/repo/migrations/20240910194615_add_recalculation_type_to_deployments.exs
> +      add(:recalculation_type, :recalculation_type, default: "broadcast", null: false)
Ya I knew exactly what I had done when seeing this vs what was in my head with "Enum" at the time 🤦🏼

2024-09-11 18:13 UTC, oestrich commented on test/nerves_hub_web/channels/websocket_test.exs
> -    test "assigned a deployment", %{user: user, tmp_dir: tmp_dir} do
Brought it back

2024-09-11 18:18 UTC, oestrich commented
Ok, there's a branch higher up at the update_deployment function. Ends up leaving most everything in place as it was, which seems like what we want? I don't think we need to change any of the device channel things because the calculator won't broadcast `deployment/changed` which triggers recalculation in the device channel itself

2024-09-11 22:10 UTC, joshk commented on lib/nerves_hub/deployments.ex
> +          |> Ecto.Changeset.put_change(:total_updating_devices, device_count)
it looks like these lines are the same for `update_deployment_calculator` and `update_deployment_broadcast`, maybe its better to move this logic to `update_deployment`

2024-09-11 22:27 UTC, jjcarstens commented on lib/nerves_hub/deployments.ex
> +          |> Ecto.Changeset.put_change(:total_updating_devices, device_count)
This is my fault. I initially stated I'd rather have duplicated code than complicated code. I think we could improve reusing this in both cases, but also fine with the simple diff I'm presented with

2024-09-11 22:27 UTC, jjcarstens commented on lib/nerves_hub/deployments.ex
> +    case deployment.recalculation_type do
I feel totally bipolar, but one thing I'm realizing now that I'm staring at this clean function is that we may not need to store this in the database at all. This could be part of the params or a function to the argument to specify which calculator route to take maybe?

On that note, we probably want a way to do this via the UI. I'm happy to add that change if you would like?

2024-09-12 15:01 UTC, oestrich commented on lib/nerves_hub/deployments.ex
> +    case deployment.recalculation_type do
I'm good with whatever in regards to the database vs param, and please do! Would make things easier haha

2024-09-15 17:58 UTC, jjcarstens commented
@oestrich @joshk Look at the changes of 21675de. I initially started by just adding the UI to set, but then found some ways to make things a little more readable and still get the `Repo.transaction` optimization.

I also kept it in the DB because when digging deeper I saw it would still be needed for the `Turn On/Off` button, so seemed better to leave in there for now

<img width="1515" alt="image" src="https://github.com/user-attachments/assets/be08c48d-8a96-4794-b974-ef4580cee5e8">

2024-09-16 00:36 UTC, joshk approved these changes

2024-09-16 14:52 UTC, merged