Device health liveview
nerves-hub/nerves_hub_web pull request #1484
Opened 2024-09-03 11:33 UTC by elinol

Adds liveview and route for device health, using Contex for rendering quite basic svg charts.

Settings available:
- Metrics for time intervals of 1 hour, 1 day or 7 days
- Scatter or line chart

2024-09-03 12:08 UTC, lawik requested changes
Good stuff!

A lot of small notes but everything seems reasonable :)

Let me know if you have any questions.

2024-09-03 12:08 UTC, lawik commented on lib/nerves_hub_web/live/devices/device_health.ex
> +          [[NaiveDateTime.from_iso8601!(timestamp), metrics["load_15min"]] | acc.load_1min]
The above will also remove the risk of oops-mappings like this 15min to 1min :)

2024-09-03 12:08 UTC, lawik commented on lib/nerves_hub_web/live/devices/device_health.ex
> +          [[NaiveDateTime.from_iso8601!(timestamp), metrics["load_5min"]] | acc.load_1min]
Get 5 min for the price of 1?

2024-09-03 12:08 UTC, lawik commented on lib/nerves_hub_web/live/devices/device_health.ex
> +          [[NaiveDateTime.from_iso8601!(timestamp), metrics["size_mb"]] | acc.load_1min]
hmm 🤔

2024-09-03 12:08 UTC, lawik commented on lib/nerves_hub_web/live/devices/device_health.ex
> +          [[NaiveDateTime.from_iso8601!(timestamp), metrics["used_mb"]] | acc.load_1min]
It shouldn't ALL be about load_1min I think :)

2024-09-03 12:08 UTC, lawik commented on lib/nerves_hub_web/live/devices/device_health.ex
> +          [[NaiveDateTime.from_iso8601!(timestamp), metrics["used_percent"]] | acc.load_1min]
:D last one

2024-09-03 12:08 UTC, lawik commented on lib/nerves_hub_web/live/devices/device_health.ex
> +    |> Enum.map(fn [_, value] -> value end)
map + max is the same as `Enum.max_by` so we could do that here and be mildly more efficient.

https://hexdocs.pm/elixir/1.12/Enum.html#max_by/4

2024-09-03 12:08 UTC, lawik commented on lib/nerves_hub_web/live/devices/device_health.ex
> +    |> then(fn value ->
Let me introduce my friend `max/2`.

```
|> max(1)
```

It will take the bigger number of whatever you got and 1. So `max(0,1)` will give `1`.

2024-09-03 12:08 UTC, lawik commented on lib/nerves_hub_web/live/devices/device_health.ex
> +       do: raw("<p class=\"metrics-text\">No data for selected period</p>")
Not sure but I think you can do `~H"..."` for this.

2024-09-03 12:08 UTC, lawik commented on lib/nerves_hub_web/live/devices/device_health.ex
> +    if connected?(socket) and device_health_check_enabled?() do
Maybe `mount` should only start this if connected?

2024-09-03 12:25 UTC, elinol commented on lib/nerves_hub/devices.ex
> +    |> Repo.all()
This is used in `NervesHub.Workers.DeviceHealthTruncationTest` so didn't want to remove it. Also, health is only kept for 7 days I think?

2024-09-03 12:29 UTC, elinol commented on lib/nerves_hub_web/live/devices/device_health.ex
> +    |> assign(:device, device)
This pattern is used in other liveviews, so figured I'd use the same. We could do a refactor of them all later if desirable?

2024-09-03 12:32 UTC, elinol commented on lib/nerves_hub_web/live/devices/device_health.ex
> +        |> Map.put(
lol, that's a great suggestion according to my mistakes in all those `Map.put`s!

2024-09-03 13:44 UTC, elinol commented on assets/css/_custom.scss
> +  &>img {
I agree!

2024-09-05 03:42 UTC, joshk requested changes
great work on this feature!

could you include a screenshot in the PR too please

my code suggestions are minor, once they are addressed I would be happy to merge this in and deploy to NervesCloud for testing

2024-09-05 03:42 UTC, joshk commented on lib/nerves_hub/devices.ex
> +    |> from()
the `from()` isn't needed as this is implicit from using `DeviceHealth`

2024-09-05 03:42 UTC, joshk commented on lib/nerves_hub/devices.ex
> +  def get_device_health(device_id), do: get_all_health(device_id)
Instead of this function pointing to `get_all_health`, I think this is the correct name for the function, which is a roundabout way of saying that the contents of `get_all_health` should be moved into here.

2024-09-05 03:42 UTC, joshk commented on lib/nerves_hub/devices.ex
> +    |> from()
same as above, `from()` isn't needed

2024-09-05 03:42 UTC, joshk commented on lib/nerves_hub_web/live/devices/device_health.ex
> +    |> assign(:device, device)
I personally prefer single line assigns. I'm happy to have a discussion on a preference.

2024-09-05 06:52 UTC, elinol commented
<img width="1444" alt="image" src="https://github.com/user-attachments/assets/dc1ab6de-670a-4666-b3f0-9259b67d8eb4">
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/718c9036-2042-4b31-b159-36bd263e4197">
<img width="1386" alt="image" src="https://github.com/user-attachments/assets/3a39a6b4-7ee2-415f-b05b-fe8d1979a900">

2024-09-05 06:53 UTC, elinol commented on lib/nerves_hub/devices.ex
> +  def get_device_health(device_id), do: get_all_health(device_id)
I like that!

2024-09-05 07:37 UTC, joshk commented on lib/nerves_hub_web/live/devices/device_health.ex
> +    if connected?(socket) and device_health_check_enabled?() do
Placing this within the mount pipe flow is a little hack so that dyalizer doesn't complain about not capturing the return value.

2024-09-05 07:38 UTC, merged