Add device count and estimated device count for Deployment views
nerves-hub/nerves_hub_web pull request #1517
Opened 2024-09-12 15:29 UTC by lawik

This allows seeing how big a deployment is in device count in listings
and detail view.

Beyond that the Edit form for Deployments will estimate the matching
devices based on the conditions set.
@lawik

2024-09-14 02:49 UTC, joshk requested changes
All in all this looks great. Just some small change suggestions.

2024-09-14 02:49 UTC, joshk commented on lib/nerves_hub/deployments.ex
> +    )
I think this query can be simplified to only use the `devices` table since that table has both `product_id` and `deployment_id`. Also, it would be good to have this in the pipe-able format for consistency.

2024-09-14 02:49 UTC, joshk commented on lib/nerves_hub/deployments.ex
> +    )
Simple to my comment above.

2024-09-14 02:49 UTC, joshk commented on lib/nerves_hub/deployments.ex
> +  def estimate_devices_hit_by_conditions(product_id, platform, conditions) do
maybe rename this to `estimate_devices_matched_by_conditions`

2024-09-14 04:52 UTC, lawik commented on lib/nerves_hub_web/live/deployments/edit.ex
> +    dbg(params["conditions"])
That's a load-bearing dbg!

2024-09-14 04:54 UTC, lawik commented on lib/nerves_hub/deployments.ex
> +    )
Huh! Did not notice that. Good catch :)

And hadn't realized there was a preferred way to Ecto. Can fix :)

2024-09-14 04:56 UTC, lawik commented on lib/nerves_hub/deployments.ex
> +  def estimate_devices_hit_by_conditions(product_id, platform, conditions) do
Sure thing :)

2024-09-25 13:20 UTC, lawik commented
Gotta make it not break also...

2024-09-25 13:22 UTC, lawik commented
And fixed :D

2024-09-25 13:31 UTC, lawik commented
Test hit a deadlock in an unrelated test so I gave it a re-run. Worth figuring out but very unlikely to be this PR?

2024-09-25 20:30 UTC, joshk reviewed
Is it worth us adding tests for this?

2024-09-25 20:30 UTC, joshk commented on lib/nerves_hub/deployments.ex
> +  def estimate_devices_matched_by_conditions(product_id, platform, conditions) do
@lawik it just occurred to me to ask, do you think this will perform well with result sets in the 200k+ range?

2024-09-25 20:46 UTC, lawik commented on lib/nerves_hub/deployments.ex
> +  def estimate_devices_matched_by_conditions(product_id, platform, conditions) do
I think it will do well enough. It will only happen as you change a deployment. So not very frequent. If it turns out to be heavy we might want to tune the debounce.

2024-09-25 20:47 UTC, lawik commented
> Is it worth us adding tests for this?

Possibly but not enough that I think anyone would care if it broke and it would take kind of weird stuff to break it.

You can make a call on this. I'll write the tests if you prefer them. For me they are smack in the do/don't split.

2024-09-25 20:58 UTC, joshk commented on lib/nerves_hub/deployments.ex
> +  def estimate_devices_matched_by_conditions(product_id, platform, conditions) do
Sweet

2024-09-25 21:00 UTC, joshk commented
Same, this is smack bang on that line. 

I'm going to skip the need for a test as we are looking at making changes to Deployments in the long run.

2024-09-25 21:00 UTC, merged