Device Connections
nerves-hub/nerves_hub_web pull request #1572
Opened 2024-10-01 08:43 UTC by elinol

For saving device connection history.

2024-10-02 07:52 UTC, elinol commented
I'm not sure if we want device location on `DeviceConnection` as `metadata`, or if it should be stored on `Device`, maybe as it's own field? A location map?

2024-10-02 09:52 UTC, elinol commented on lib/nerves_hub_web/channels/device_socket.ex
>        {:ok, _device} = Devices.device_heartbeat(device)
To be removed

2024-10-28 06:10 UTC, joshk requested changes
All in all I love the direction. 
I'm more than happy to jump on a zoom and go over the feed.

2024-10-28 06:10 UTC, joshk commented on lib/nerves_hub_web/channels/device_socket.ex
> -      |> assign(:reference_id, generate_reference_id())
Instead of removing this assigns, you can change it to `:connection_information` and store the `DeviceConnection`, which we can then use for the device heartbeat.
eg. `Connections.device_heartbeat(socket.assigns.connection_information)`

2024-10-28 06:10 UTC, joshk commented on lib/nerves_hub_web/channels/device_socket.ex
> -      |> assign(:reference_id, generate_reference_id())
Ahhhh, I see this is being done on line 210.

The `reference_id` can be used in the `device_heartbeat` function

2024-10-28 06:10 UTC, joshk commented on lib/nerves_hub_web/channels/device_socket.ex
> +    |> assign(:connection_established_at, established_at)
I don't think we need to store this or use it, thoughts?

2024-10-28 06:10 UTC, joshk commented on lib/nerves_hub/devices/device_connection.ex
> +  @primary_key {:id, :binary_id, autogenerate: true}
I would recommend using https://github.com/martinthenth/uuidv7 as v7 UUIDs are sortable due to how the timestamp is at the front of the generated code

2024-10-28 08:26 UTC, elinol commented on lib/nerves_hub/devices.ex
> +    |> preload(device_connections: ^Connections.latest_connection_preload_query())
this functions has two callers only: the dashboard which is using the connection info, and the index function from device controller which I figured also should have this info included (not completely sure on this). That's why I added the preload here.

2024-10-28 08:54 UTC, elinol commented on lib/nerves_hub/devices.ex
> +    |> preload(device_connections: ^Connections.latest_connection_preload_query())
As above, this is because connection info is wanted when asking for the device list.

2024-10-28 11:15 UTC, elinol commented on lib/nerves_hub/deployments/calculator.ex
> +            |> preload(:device_connections)
If we'll use a status field on device for seen/not seen (just registered/connected) we would not need a preload at all.

2024-10-28 12:53 UTC, elinol commented on lib/nerves_hub_web/channels/device_socket.ex
> +    |> assign(:connection_established_at, established_at)
I think it's good to have the established_at information on every DeviceConnection record to not need to make separate calls to db for `last_seen_at`and `established_at`.

2024-10-28 12:56 UTC, elinol commented on lib/nerves_hub/devices/device_connection.ex
> +  @primary_key {:id, :binary_id, autogenerate: true}
oh I thought this was set as default when using binary ids, couldn't find any other schemas where it was defined

2024-11-04 02:42 UTC, joshk requested changes
I think we are nearly there!

This is great work!

2024-11-04 02:42 UTC, joshk commented on lib/nerves_hub/deployments/calculator.ex
> +            |> preload(:device_connections)
Following up on a chat we had, lets add two new fields to the Device schema, `status` (`registered` and `provisioned`) and `first_seen_at` (DateTime)

2024-11-04 02:42 UTC, joshk commented on lib/nerves_hub_web/live/devices/device_health.ex
> +    |> assign(:connection_established, Connections.get_established_at(device.id))
This should probably be changed to something like:
```elixir
|> assign(:latest_connection, Connections.get_latest_for_device(device.id))
```

2024-11-04 02:42 UTC, joshk commented on lib/nerves_hub_web/live/devices/index.html.heex
> +              <span title={if device.device_connections != [], do: "Last seen at #{device.device_connections |> hd |> Map.get(:last_seen_at) |> DateTimeFormat.from_now()}", else: "Not seen yet"} }>
The multiple piping is a bit messy, can you create a helper function for this instead.

2024-11-04 02:42 UTC, joshk commented on lib/nerves_hub_web/live/devices/show.ex
>      {:noreply, assign(socket, :device, device)}
I think line 62 can be merged into the piping above:
```elixir
    socket
    |> assign(:device, device)
    |> assign(:device_connection, Connections.get_latest_for_device(device.id))
    |> noreply()
```

2024-11-05 17:51 UTC, jjcarstens commented on lib/nerves_hub/devices/device.ex
> +    )
This might be offloading `:status` a bit. With this, it will not match the [device#show `:status` assigns](https://github.com/nerves-hub/nerves_hub_web/pull/1572/files#diff-7aac782381f55c9784ae6d3201da689e8c17034ae359b1d4c8a8a58cdbc42c25R36) or the `Tracker.status/1` which is always `"online" | "offline"`

2024-11-05 23:10 UTC, joshk requested changes

2024-11-05 23:10 UTC, joshk commented on lib/nerves_hub_web/live/devices/show.ex
>      |> assign(:status, Tracker.status(device))
could we rename this to `connection_status`?

2024-11-05 23:11 UTC, joshk commented on lib/nerves_hub/devices/device.ex
> +    )
I've suggested we change the assigns you have linked to to instead be named `connection_status`.

2024-11-05 23:14 UTC, joshk requested changes

2024-11-05 23:14 UTC, joshk commented on priv/repo/migrations/20241104095030_add_status_and_first_seen_at_to_devices.exs
> +      add(:first_seen_at, :utc_datetime)
We should add an `execute` to set a value for `first_seen_at`. We can use the `inserted_at` field if the devices `connection_status` value isn't `not_seen`. Thoughts?

2024-11-06 00:55 UTC, joshk commented on lib/nerves_hub/tracker.ex
> +    Connections.get_current_status(device.id) == :connected
@elinol we preload the latest device connection, can we use that instead of loading from the DB?

2024-11-11 17:09 UTC, elinol commented on priv/repo/migrations/20241104095030_add_status_and_first_seen_at_to_devices.exs
> +      add(:first_seen_at, :utc_datetime)
sounds good

2024-11-12 22:41 UTC, joshk commented
@elinol I've left a couple of comments, and I see a couple of comments not resolved. Happy to jump on a Zoom if it helps. I think we are nearly there. I need to check with Jon regarding the use of Tracker, but for now I think we should keep it.

2024-11-13 13:52 UTC, elinol commented on lib/nerves_hub_web/live/devices/show.ex
>      |> assign(:status, Tracker.status(device))
I ended up with removing the status assign since the status is already included in `:device_connection`

2024-11-14 08:40 UTC, joshk commented on lib/nerves_hub/tracker.ex
> -    _ = Phoenix.PubSub.broadcast(NervesHub.PubSub, "device:#{device.id}", :online?)
@jjcarstens can we chat about this tomorrow? (your today)

2024-11-14 22:06 UTC, joshk commented on lib/nerves_hub/tracker.ex
> -    _ = Phoenix.PubSub.broadcast(NervesHub.PubSub, "device:#{device.id}", :online?)
Spoke with Jon, we are fine with removing this and doing a bigger refactor and rethink of Tracker in the very near future.

2024-11-14 23:00 UTC, joshk approved these changes
I think this is good to go!

We can monitor it in prod and make sure we have covered all our bases.

2024-11-15 03:36 UTC, joshk commented
@elinol sorry, during my rebase I've broken the test suite, could you please help fix it? sorry.

2024-11-15 07:59 UTC, elinol commented
@joshk no problems, it's done!

2024-11-16 03:56 UTC, joshk commented
Awesome, thank you!

2024-11-16 03:56 UTC, merged

2024-11-16 03:56 UTC, joshk commented
🎉