Add option for showing updated devices on the map
nerves-hub/nerves_hub_web pull request #1592
Opened 2024-10-09 09:40 UTC by lawik

This adds a way to indicate if the firmware is fully up to date on devices for the map.

It also cleans up a few performance aspects of the map:
- Don't block initial load on fetching the devices/markers as it can be slow for many devices
- Change query to be more specific and not fetch as many unused devices
- Change data-plumbing so that markers are sent over push_event instead of via attributes with extra JSON encode/decode.

The map should load significantly faster and will indicate "Loading..." while loading if delayed.

We should further check index usage for these new queries as I think they could be made even faster if they don't have indexes today.

2024-10-09 09:41 UTC, lawik commented
This should be both useful, nice for people sending out deployments (see them take effect live) and it should make for a heck of a demo. Unfortunately there are a number of tests that are broken by the change in initial load behavior. The tests are all for the dashboard so I'm inclined to disable them for now as we know we will change the dashboard a lot.

2024-10-10 00:41 UTC, joshk requested changes
I haven't tested this locally.
Why was the test file for the dashboard removed?
I don't think this is ready to be merged in, but I would be happy to deploy this to its own app for demo use?

2024-10-10 00:41 UTC, joshk commented on lib/nerves_hub/devices.ex
> +    from(d in Device)
this can be just `Device`

2024-10-10 00:41 UTC, joshk commented on assets/js/app.js
> +    window.addEventListener(
There is a nicer way of doing this. Instead of adding an event listener on the winder, you can add d something like this:
```javascript
    this.handleEvent('update-markets', (data) => {
      this.map.updateMarkers(data);
    });
```
Then you can have an `updateMarkers` function attached to the map class.

2024-10-10 00:41 UTC, joshk commented on assets/js/app.js
> +    window.addEventListener(
Similar to what is done on https://github.com/nerves-hub/nerves_hub_web/pull/1592/files#diff-2126216ecd2ff9ae9b5f0c1e84d8fecb4ee4e54dc21685f69a590c2162dec186R147-R152

2024-10-10 04:42 UTC, lawik commented
> I haven't tested this locally. Why was the test file for the dashboard removed? I don't think this is ready to be merged in, but I would be happy to deploy this to its own app for demo use?

I mentioned the tests breaking in the initial comment. The loading order was changed to start blank as a large initial load could hang the LiveView for longer. The change in behavior invalidsted the tests. I am not sure how to fix those tests (maybe easy if you are used to testing LiveViews but what I tried didn't work) and I think the dashboard view will churn a lot so not sure if those tests are worth reviving. But if it is easy, we can certainly do it.

I tagged this so a container got built and have tried it on NervesCloud. Works well. Performs better than the previous version.

2024-10-10 04:43 UTC, lawik commented on lib/nerves_hub/devices.ex
> +    from(d in Device)
Right you are

2024-10-10 04:44 UTC, lawik commented on assets/js/app.js
> +    window.addEventListener(
Cool. I grabbed what they suggested in LiveView docs :D but will fix that for sure

2024-10-11 01:41 UTC, joshk commented on lib/nerves_hub_web/live/dashboard/index.ex
> -    |> subscribe_to_devices()
I have an idea!
don't remove this, but follow my second comment

2024-10-11 01:41 UTC, joshk commented on lib/nerves_hub_web/live/dashboard/index.ex
> -    |> subscribe_to_devices()
create a new function, similar to this:
```elixir
defp subscribed?(device) do
  Registry.count_select(NervesHub.PubSub, [{{"device:#{device.identifier}:internal", self(), :_}, [], [true]}]) > 0
end
```
and then on https://github.com/nerves-hub/nerves_hub_web/pull/1592/files#diff-4e1dd445a5a9fb5ca7c2ab2056a5820eea96b0bb22995b6e423c3cf818978fd1R69, check if the device is subscribed first.

2024-10-11 01:42 UTC, joshk commented
> > I haven't tested this locally. Why was the test file for the dashboard removed? I don't think this is ready to be merged in, but I would be happy to deploy this to its own app for demo use?
> 
> I mentioned the tests breaking in the initial comment. The loading order was changed to start blank as a large initial load could hang the LiveView for longer. The change in behavior invalidsted the tests. I am not sure how to fix those tests (maybe easy if you are used to testing LiveViews but what I tried didn't work) and I think the dashboard view will churn a lot so not sure if those tests are worth reviving. But if it is easy, we can certainly do it.
> 
> I tagged this so a container got built and have tried it on NervesCloud. Works well. Performs better than the previous version.

could we undelete the test file and add a tag to ignore the tests temporarily?

2024-10-11 13:50 UTC, lawik commented
I should still undelete the test file and I need to test these changes on an environment where I have an easier time triggering changes. But this **should** do what we want and never refresh more frequently than 500ms.

2024-10-12 00:54 UTC, joshk approved these changes
Looks great.

I'd still like to bring back the test file and just skip the tests, but I'm also fine with removing it as we will need to revamp this page soon.

2024-10-12 05:52 UTC, lawik commented
We can revive it if we find it useful later :)

2024-10-12 05:52 UTC, merged