World Map clustering
nerves-hub/nerves_hub_web pull request #1619
Opened 2024-10-29 14:31 UTC by lawik

See video here: https://github.com/nerves-hub/nerves_hub_web/pull/1611

I tested this with 180.000 active and connected devices (faked). It loaded consistently but took a decent number of seconds. It was much faster down towards 50.000 and snappy below those types of numbers.

Once loaded it becomes easy to navigate and performant. I think this works. We could look at faster options. But the clustering makes 180K possible where it isn't without it.

We could try various things to constrain how many we load. I've looked at recommendations for performance and applied what I found. chunkedLoading option keeps it responsive while loading, renderer using Canvas makes it more performant.

I cut down heavily on non-used values because the first JSON transfer was 18 Mb and I think I got it down to about 1Mb for 180K. Maybe we could win more there with compression. That wasn't the slow part for me.

2024-11-02 05:47 UTC, joshk requested changes

2024-11-02 05:47 UTC, joshk commented on mix.lock
> +  "phoenix_test": {:hex, :phoenix_test, "0.3.2", "030d98c401ef95db564da6a15b5077909e11a532986690b757f40c105cda8be4", [:mix], [{:floki, ">= 0.30.0", [hex: :floki, repo: "hexpm", optional: false]}, {:j
Updating `phoenix_test` is not possible right now. You will need to revert this update if you want the test suite to pass.

2024-11-02 06:20 UTC, lawik commented on mix.lock
> +  "phoenix_test": {:hex, :phoenix_test, "0.3.2", "030d98c401ef95db564da6a15b5077909e11a532986690b757f40c105cda8be4", [:mix], [{:floki, ">= 0.30.0", [hex: :floki, repo: "hexpm", optional: false]}, {:j
Ah, I had to nuke and pave deps for some ungodly state they got stuck in but happy to revert that.

2024-11-11 09:59 UTC, lawik commented
@joshk this will be squashed and so on, but I think you should try the functionality, see how you like it :)

2024-11-12 08:49 UTC, lawik commented
Should be good to go. Ideally take a look and see how you enjoy it @joshk :)

2024-11-14 21:14 UTC, nshoes commented on assets/js/app.js
> +    var clusterLayer = L.markerClusterGroup({ chunkedLoading: true, chunkProgress: this.updateProgressBar });
This was difficult for me to read, so I ran through it and made some adjustments:

```js
var defaultOptions = {
  radius: 6,
  weight: 1,
  opacity: 0,
  fillOpacity: 1,
  renderer: myRenderer,
  fillColor: "#4dd54f"
}

var markerOfflineColor = "rgba(196,49,49,1)"
var markerOutdatedColor = "rgba(99,99,99,1)"

var devices = this.markers.reduce(function(acc, marker) {
  let location = marker["l"]
  var latLng = [location["at"], location["ng"]]

  // if no location or we don't care about mode, move on
  if (!location["ng"] && !location["at"]) return acc
  if (!["connected", "updated"].includes(mode)) return acc

  if (marker["s"] == "connected") {
    return L.circleMarker(latLng, defaultOptions)
  } else if (mode == "connected") {
    return L.circleMarker(latLng, Object.assign(defaultOptions, { fillColor: "rgba(196,49,49,1)" }))
  } else if (mode =="updated") {
    return L.circleMarker(latLng, Object.assign(defaultOptions, { fillColor: "rgba(99,99,99,1)" }))
  }
}, [])
```

It's not tested but it's close. Let me know what you think!

2024-11-14 21:14 UTC, nshoes commented on lib/mix/tasks/gen.devices.ex
> +defmodule Mix.Tasks.Gen.Devices do
I wrote something similar this morning seeding thousands of devices locally; this is nice!

2024-11-14 21:14 UTC, nshoes commented on lib/nerves_hub_web/live/dashboard/index.ex
> +  @default_refresh 50000
Any reason for picking 50 seconds? My brain wants this to be 45 or 60s 😆, but I don't feel strongly.

2024-11-14 21:14 UTC, nshoes commented on lib/nerves_hub_web/live/dashboard/index.ex
> +           identifier: _identifier,
```suggestion
```

2024-11-14 21:14 UTC, nshoes commented on assets/js/app.js
> +      }
Did this not work properly with your changes?

2024-11-21 12:47 UTC, lawik commented on assets/js/app.js
> +    var clusterLayer = L.markerClusterGroup({ chunkedLoading: true, chunkProgress: this.updateProgressBar });
good stuff, reworked a bit but a similar thing will be there :)

2024-11-21 12:53 UTC, lawik commented
@nshoes looked at your notes, fixed all of it I believe :)

2024-11-21 16:49 UTC, nshoes commented on lib/nerves_hub_web/live/dashboard/index.ex
> +  @default_refresh 50000
No no no please no I don't feel that strongly 😆😆😆

2024-11-21 16:51 UTC, nshoes approved these changes
🚀 🚀 🚀 🚀 🚀

2024-11-21 17:07 UTC, lawik commented
Need to fix CI though

2024-11-21 20:53 UTC, nshoes commented
@lawik done! :)

2024-11-22 10:12 UTC, merged