Show helpful message when uploading duplicate firmware
nerves-hub/nerves_hub_web pull request #1627
Opened 2024-10-31 23:50 UTC by nshoes

This adds an error clause to provide helpful feedback when uploading firmware that has already been uploaded. [There's already a test for this constraint](https://github.com/nerves-hub/nerves_hub_web/blob/b7efd90ff828c0a6ee52b0b40ba3065cd68b6985/test/nerves_hub/firmwares_test.exs#L53), but let me know if a LiveView test is wanted/needed.

![CleanShot 2024-10-31 at 16 45 39](https://github.com/user-attachments/assets/5279fcef-9dc5-419e-8b32-07110d3b5bed)

2024-11-01 14:28 UTC, jjcarstens commented on lib/nerves_hub_web/live/firmware.ex
> +        error_feedback(socket, "Duplicate firmware uploads are not allowed")
Do we get the uuid back in that changeset somewhere? It would be really cool to say something like `Duplicate firmware - <link-to-firmware>`

2024-11-01 14:52 UTC, nshoes commented on lib/nerves_hub_web/live/firmware.ex
> +        error_feedback(socket, "Duplicate firmware uploads are not allowed")
Oh, good idea! I'll try.

2024-11-01 15:37 UTC, nshoes commented on lib/nerves_hub_web/live/firmware.ex
> +        error_feedback(socket, "Duplicate firmware uploads are not allowed")
Done! Updated the gif in the PR description.

2024-11-02 05:28 UTC, joshk requested changes

2024-11-02 05:28 UTC, joshk commented on lib/nerves_hub_web/live/firmware.ex
> +          "Duplicate firmware - <a href='#{route}' target='blank'>View Firmware</a>"
I'd prefer to find a way to not include an `<a href>` in a string error message, and then also use `raw` for displaying the message.

It might require a little refactoring, eg. instead of line 164 adding an error message to the assigns, maybe we add an `error_code`, like `:duplicate_firmware` and then use a helper function in the template which uses a `case` statement to define the long form message.

2024-11-04 14:13 UTC, nshoes commented on lib/nerves_hub_web/live/firmware.ex
> +          "Duplicate firmware - <a href='#{route}' target='blank'>View Firmware</a>"
I like that a lot more, I'll implement!

2024-11-04 22:17 UTC, nshoes commented on lib/nerves_hub_web/live/firmware.ex
> +          "Duplicate firmware - <a href='#{route}' target='blank'>View Firmware</a>"
Changes pushed. I think instead of handling this scenario in a pattern-match with `error_feedback`, it could just be handled inline since we have to pattern-match on the UUID error and then pattern-match it again which feels weird. Lmk what you think!

2024-11-04 23:04 UTC, jjcarstens commented on lib/nerves_hub_web/live/firmware.ex
> +    )
```suggestion
    |> assign(:error_code, {:duplicate_firmware, uuid})
```

Since we have control of this structure, we could just include the duplicate UUID and let the case handling of that view build the URL for it (or whatever else). That way we're not so coupled to 2 independent pieces of data having to exist in the assigns (`@error_code` and `@firmware_path`)

2024-11-05 23:02 UTC, joshk approved these changes
This generally looks good to me

2024-11-05 23:03 UTC, merged