Add support for filtering devices on alarms
nerves-hub/nerves_hub_web pull request #1628
Opened 2024-11-01 10:17 UTC by elinol

Adds filtering support for:
- Devices with alarms / without alarms
- Devices with specific alarms (list with current alarm types for product)

Also adds alarm counter on product dashboard with link to filtered devices list.

2024-11-01 10:19 UTC, elinol commented on lib/nerves_hub/devices/alarms.ex
> +      Map.keys(data["alarms"])
Currently in this format: `NervesHubHealth.HealthCheckFailed`
We could make them more human friendly perhaps?

2024-11-01 10:21 UTC, elinol commented
Looks alright in dropdown selector:
![image](https://github.com/user-attachments/assets/53ca2d25-7930-40de-a433-b395eef5768c)

But not when selected:
![image](https://github.com/user-attachments/assets/852bacec-0a80-4eda-b037-7d9bf6d4ac7d)

Worth it to fix now or wait for UI update?

2024-11-01 13:56 UTC, jjcarstens commented on lib/nerves_hub/devices/alarms.ex
> +      Map.keys(data["alarms"])
Using `inspect/1` on the alarm name will pretty print without `Elixir.` - We could also add a helper in `DeviceHealth.save/1` to preemptively adjust/cast `:alarms` keys into the prettier format

2024-11-02 05:36 UTC, joshk requested changes

2024-11-02 05:36 UTC, joshk commented on lib/nerves_hub/devices/alarms.ex
> +    from(
Could we change this only to use piped queries instead of the mix of the two.

2024-11-02 05:36 UTC, joshk commented on lib/nerves_hub/devices/alarms.ex
> +    from(
same as above

2024-11-02 05:36 UTC, joshk commented on lib/nerves_hub/devices/alarms.ex
> +      Map.keys(data["alarms"])
I'm wondering if we also remove `NervesHubHealth`?

2024-11-04 09:08 UTC, elinol commented on lib/nerves_hub/devices/alarms.ex
> +      Map.keys(data["alarms"])
Oh, it's `Elixir.NervesHubHealth.HealthCheckFailed` actually so solved it by splitting on dots and using the last item.

2024-11-04 09:08 UTC, elinol commented on lib/nerves_hub/devices/alarms.ex
> +    from(
yes!

2024-11-04 09:59 UTC, joshk requested changes

2024-11-04 09:59 UTC, joshk commented on lib/nerves_hub/devices/alarms.ex
> +    |> from()
Is this `from()` needed?

2024-11-04 09:59 UTC, joshk commented on lib/nerves_hub/devices/alarms.ex
> +    from(
Can you please switch these to pipe queries.

2024-11-04 10:00 UTC, elinol commented on lib/nerves_hub/devices/alarms.ex
> +    |> from()
yes

2024-11-04 10:07 UTC, elinol commented on lib/nerves_hub/devices/alarms.ex
> +    from(
I can! I found this way easier to follow somehow

2024-11-04 20:42 UTC, jjcarstens commented on lib/nerves_hub/devices/alarms.ex
> +      Map.keys(data["alarms"])
Will there be more alarms in the future? We have lots of alarms not explicitly scoped to `NervesHubHealth`. I'm not sure if that's the only thing expected to be reported here though the name `alarms` seems to suggest it might

2024-11-05 07:29 UTC, elinol commented on lib/nerves_hub/devices/alarms.ex
> +      Map.keys(data["alarms"])
From what I understand the alarm functionality will be built out, and separated into it's own context. This functions will need an update then :)

2024-11-05 23:07 UTC, joshk approved these changes
This is a solid step forward!

2024-11-12 08:13 UTC, lawik commented on lib/nerves_hub/devices/alarms.ex
> +      Map.keys(data["alarms"])
NervesHubHealth came from the separate library that we won't be shipping. We can go forward with whatever naming we prefer.

2024-11-12 08:14 UTC, lawik commented on lib/nerves_hub/devices/alarms.ex
> +      Map.keys(data["alarms"])
I agree with using `inspect/1` to get it without the Elixir prefix :)

2024-11-12 08:16 UTC, lawik commented
So the NervesHubHealth prefix for the alarm is entirely up to the thing making the alarm. We can decide if we want a different convention in the default alarms for NervesHubLink as we won't be shipping the NervesHubHealth library. It got folded into NervesHubLink's features implementation.

2024-11-12 11:19 UTC, elinol commented
![image](https://github.com/user-attachments/assets/8efe51a3-e662-47db-8e13-63c9d90544bd)

2024-11-14 09:04 UTC, joshk approved these changes
Looks great to me. Some of the Ecto bits are bending my brain, but I think we can try this out in prod and improve from there.

2024-11-14 09:39 UTC, elinol commented
@joshk this should be ready now!

2024-11-14 22:33 UTC, merged

2024-11-14 22:34 UTC, joshk commented
Awesome work @elinol !