Don't recalculate deployments for devices
nerves-hub/nerves_hub_web pull request #1652
Opened 2024-11-20 17:07 UTC by nshoes

2024-11-20 23:22 UTC, jjcarstens approved these changes
LGTM! A couple things I noticed which may have been addressed, but just confirming

2024-11-20 23:33 UTC, nshoes commented on lib/nerves_hub_web/channels/device_channel.ex
> +    device = if device.deployment_id, do: device, else: Deployments.set_deployment(device)
We haven't discussed this specifically, no.

> besides abundance of caution to prevent firmware starting to download we know we fail

That's more than enough reason for me.

2024-11-20 23:41 UTC, nshoes commented on lib/nerves_hub_web/channels/device_channel.ex
> -  def handle_in("check_update_available", _params, socket) do
Oh duh, that makes sense. I thought this was cruft since there were no internal calls with `check_update_available`. When would a device request this? I don't see any calls to this in `cloud_bridge` or `nerves_hub_link`. I'm down to keep this around if it's used (minus recalc things).

2024-11-21 00:06 UTC, nshoes commented on lib/nerves_hub_web/channels/device_channel.ex
> -  def handle_in("check_update_available", _params, socket) do
This code path is linked to a [nerves_hub_link issue that hasn't been fixed](https://github.com/nerves-hub/nerves_hub_link/issues/47) yet, so I'll bring this back.

2024-11-21 01:51 UTC, joshk commented on lib/nerves_hub_web/channels/device_channel.ex
> +    device = if device.deployment_id, do: device, else: Deployments.set_deployment(device)
Hmmmmmm, when you say `we know we fail`, could you give an example of how this might happen?

2024-11-21 01:53 UTC, joshk commented on lib/nerves_hub_web/channels/device_channel.ex
> -  def handle_in("check_update_available", _params, socket) do
I think this is safe to remove. This was added by me a while ago based on the idea that a device could check if there is an update and make sure it has a current and valid signed download url, but after talking with Frank (and Jon) the preference was that Hub should tell the device that it should update, which moves the smarts from the device to hub. I didn't get to complete the changes in Link, so I think we could remove this.

2024-11-21 02:58 UTC, joshk requested changes
I love this PR sooooo much!

Removing code and complexity is wonderful!

One thing we should include is changing the tags and version constraint UI bits to be in their own grouping which also explains that its only used for matching when the device is not assigned to a deployment.

2024-11-21 02:58 UTC, joshk commented on priv/repo/migrations/20241120211102_remove_deployments_recalculation_type.exs
> +defmodule NervesHub.Repo.Migrations.RemoveDeploymentsRecalculationType do
We might want to leave this for a slightly later PR, as it came cause some transient errors when deploying to production.

2024-11-21 03:07 UTC, jjcarstens commented on lib/nerves_hub_web/channels/device_channel.ex
> +    device = if device.deployment_id, do: device, else: Deployments.set_deployment(device)
Digging into it deeper, there are 3 main things which could fail (2 are from [fwup specific check](https://github.com/nerves-project/nerves_system_rpi0/blob/main/fwup.conf#L373) when applying firmware)
* Platform doesn't match.
  * This is typically the Elixir app name and the NervesHub product
  * `fwup` will fail this
* Architecture doesn't match (`arm` vs `x86_64`, etc)
  * For serial numbers from crypto chips, this would never happen. For people managing serial numbers manually view a writeable file or other means, you could inadvertently reuse an old serial on a difference architecture device
  * `fwup` will fail this
* Reported firmware version no longer meets the deployment version requirement
  * i.e. I might assign a never-connected device to this deployment, but if it is <= 1.0, I don't want it to use this deployment firmware

I think the first 2 are mostly avoidable. If you move a device (i.e change the product), [deployment is removed](https://github.com/nerves-hub/nerves_hub_web/blob/main/lib/nerves_hub/devices.ex#L1022). And different arch is _highly_ unlikely. My first thought with these is I don't remember _how early_ we fail. If it is "download the whole file, then fail", then that's a lot of wasted bytes for devices on cellular.

So maybe it is if we want to consider a version check on device connect. We had previously talked about version checks and it's wishy-washy right now, so maybe we punt and see what we run into.

2024-11-21 03:35 UTC, joshk commented on lib/nerves_hub_web/channels/device_channel.ex
> +    device = if device.deployment_id, do: device, else: Deployments.set_deployment(device)
Isn't the Platform and Arch configured once and once only?

And regarding the version check, has SmartRent ever added a Version condition to an existing Deployment which has Devices associated with it?

2024-11-21 03:40 UTC, joshk commented on lib/nerves_hub_web/channels/device_channel.ex
> +    device = if device.deployment_id, do: device, else: Deployments.set_deployment(device)
Also, regarding the code, I think:
```
device = Deployments.maybe_set_deployment(device)
```
would be nicer. You can move the `if` clause into that function, which feels slightly tidier.

2024-11-21 03:42 UTC, jjcarstens commented on lib/nerves_hub_web/channels/device_channel.ex
> +    device = if device.deployment_id, do: device, else: Deployments.set_deployment(device)
If I re-burn an SD card with a different firmware project, platform is overwritten.

We use version conditions, but need to ask if we've altered the version condition of _existing_ deployment past the initial create

2024-11-21 03:53 UTC, joshk commented on lib/nerves_hub_web/channels/device_channel.ex
> +    device = if device.deployment_id, do: device, else: Deployments.set_deployment(device)
ahhhh, hmmmm, ok, it might be worth validating if a device can still belong in a deployment. I guess this is a fair safety net to keep in place.

2024-11-21 03:58 UTC, jjcarstens commented on lib/nerves_hub_web/channels/device_channel.ex
> +    device = if device.deployment_id, do: device, else: Deployments.set_deployment(device)
Ya. We can do it without extra DB work. But...what is our action if it _doesn't_ belong anymore?

2024-11-21 04:11 UTC, joshk commented on lib/nerves_hub_web/channels/device_channel.ex
> +    device = if device.deployment_id, do: device, else: Deployments.set_deployment(device)
I think the code would become something like:
```elixir
device = 
  device
  |> Deployments.verify_deployment_membership()
  |> Deployments.maybe_set_deployment()
```

2024-11-21 05:19 UTC, jjcarstens commented on lib/nerves_hub_web/channels/device_channel.ex
> +    device = if device.deployment_id, do: device, else: Deployments.set_deployment(device)
Sorry, I meant what do we do with the unmatched deployment? Just remove it, ignore, put in penalty box, some new status?

As far as code, I agree with Nate's original. The conditional of setting the deployment is really only relevant here. We would end up making a single use function and continuing to bloat a context which I already have strong feelings against typical context use anyway 😉 But just my 2¢ and I'll be happy with whatever is needed to progress

2024-11-21 23:09 UTC, nshoes commented on priv/repo/migrations/20241120211102_remove_deployments_recalculation_type.exs
> +defmodule NervesHub.Repo.Migrations.RemoveDeploymentsRecalculationType do
Done! Good callout.

2024-11-21 23:12 UTC, nshoes commented on lib/nerves_hub_web/channels/device_channel.ex
> +    device = if device.deployment_id, do: device, else: Deployments.set_deployment(device)
I just implemented:
- if device firmware doesn't match deploy firmware, remove device from deployment
- look for and set alternate deployment

2024-11-22 22:26 UTC, nshoes commented on lib/nerves_hub_web/channels/device_channel.ex
> +    device = if device.deployment_id, do: device, else: Deployments.set_deployment(device)
After thinking about this and talking to Jon, I say we go a different route: if a device's platform/arch doesn't match, we remove it from the deployment and flag the device properly. I'm not sure _how_ we want to do it though. The `status` is taken and a device is in the penalty box if `updates_blocked_until` is in the future.

Unless there's something I'm missing, I'd like to add `deployment_stalled_reason` to `device` to indicate why a device isn't on the deployment happy path. In the new world we'll track the higher-level deployment status in `deployment_release.status`, but I want to add additional context at the device level. This would also allow us to expand deployment failure reasons in the future and bubble up useful device info when viewing a deployment: "5 devices in penalty box, 2 devices separated from deployment".

Thoughts?

2024-11-22 23:15 UTC, jjcarstens commented on lib/nerves_hub_web/channels/device_channel.ex
> +    device = if device.deployment_id, do: device, else: Deployments.set_deployment(device)
Sounds great to me. Happy with the name, but for the sake of spit-balln' here is a few more:
* `:deployment_conflict`
* `:deployment_problem`
* `deployment_confidence: :valid | :bad_arch | :bad_platform | ...`
* Adding some iteration of the above to the `:status` field (which may be bad cause I'm not 100% sure what that is supposed to be for)

2024-11-23 13:42 UTC, nshoes commented on lib/nerves_hub_web/channels/device_channel.ex
> +    device = if device.deployment_id, do: device, else: Deployments.set_deployment(device)
`status` is being used for Device Connections currently, we should probably name that column better.

I like `deployment_conflict`, thanks for the suggestions.

2024-11-26 19:39 UTC, nshoes commented on lib/nerves_hub_web/channels/device_channel.ex
> +    device = if device.deployment_id, do: device, else: Deployments.set_deployment(device)
We now set `device.deployment_conflict` when deployment doesn't match. Current options are `bad_platform`, `bad_architecture`, and `bad_architecture_and_platform`.

2024-11-26 19:45 UTC, nshoes commented on lib/nerves_hub/devices.ex
> +        # Deployments.set_deployment(updated)
What should we do here after we move a device? Before it would attempt to find an alternate deployment. Setting `device.deployment_conflict` feels wrong but only semantically; there isn't an issue with the deployment, but flagging it as `:moved` feels right. Maybe we should rename the column?

2024-12-04 04:57 UTC, joshk requested changes
In addition to my inline comments, we should update https://github.com/nerves-hub/nerves_hub_web/pull/1652/files#diff-214ee95769df74267dd420f9042d92be3bc8543f4942bf9049d63577b9aa54edR46 to explain how tags are only used for matching when a device doesn't have a deployment. I think it would be best to move the `Distributed to` and `Version requirement` information to a new section called `Device matching conditions` and place the information before the current `Deployment details` section.

We should also do something similar to the 'New deployment' workflow:
<img width="1163" alt="Screenshot 2024-12-04 at 5 57 06 PM" src="https://github.com/user-attachments/assets/b0a10021-6985-4698-b853-ed1039926b8e">

2024-12-04 04:57 UTC, joshk commented on lib/nerves_hub/devices.ex
> +        # Deployments.set_deployment(updated)
I'm wondering if we don't find a deployment for the device and leave that for when it connects again.
I'm also thinking that we keep that broadcast, but instead of finding a new deployment, we instead disconnect the device and have it reconnect since the device is now bound to a new product.
Thoughts?

2024-12-04 04:57 UTC, joshk commented on lib/nerves_hub/devices/device.ex
> +    field(:deployment_conflict, Ecto.Enum,
Can you tell me more about why this column was added?

2024-12-04 04:57 UTC, joshk commented on lib/nerves_hub_web/channels/device_channel.ex
> +      |> Deployments.verify_deployment_membership()
```suggestion
    device = Deployments.verify_deployment_membership(device)
```
I think this is a bit cleaner.

2024-12-04 04:57 UTC, joshk commented on lib/nerves_hub_web/live/deployments/edit.html.heex
>    <h3 class="mb-2">Conditions</h3>
I think we could change the header to be a bit more specific, and keep the description (deleted below) but change it to provide further information on how this works.

eg. `Device matching conditions`

`These conditions are used for matching devices which don't have a configured deployment. The matching is undertaken when a device connects to the platform.`

2024-12-04 18:34 UTC, nshoes commented on lib/nerves_hub_web/channels/device_channel.ex
> +      |> Deployments.verify_deployment_membership()
Agreed! Brain fart for me :P

2024-12-04 18:45 UTC, nshoes commented on lib/nerves_hub/devices.ex
> +        # Deployments.set_deployment(updated)
Ah! I really like that, I'll implement.

2024-12-04 19:07 UTC, nshoes commented on lib/nerves_hub/devices/device.ex
> +    field(:deployment_conflict, Ecto.Enum,
We set this column when [verifying deployment membership](https://github.com/nerves-hub/nerves_hub_web/pull/1652/files#diff-48cec1d45c7f0dac953ea8a89cecbf1c568e6a9b61b02a863a3ac4c23fb68920R307) if the architecture and/or platform doesn't match. We can then surface why the device isn't in a deployment and make it easy to find and search devices that aren't a part of a deployment.

2024-12-04 22:23 UTC, nshoes commented on lib/nerves_hub_web/live/deployments/edit.html.heex
>    <h3 class="mb-2">Conditions</h3>
Done!

2024-12-04 22:26 UTC, nshoes commented on lib/nerves_hub/devices.ex
> +        # Deployments.set_deployment(updated)
What's the need for disconnecting and then reconnecting? When a device is moved, its `deployment_id` is cleared so there's no need to verify its deployment membership or any other function of `DeviceChannel`'s `after_join`. I could very well be missing something, but this is why I suggested we flag the device as `:moved`.

2024-12-04 22:28 UTC, nshoes commented on lib/nerves_hub_web/live/deployments/edit.html.heex
>    <h3 class="mb-2">Conditions</h3>
<img width="1204" alt="CleanShot 2024-12-04 at 14 28 06@2x" src="https://github.com/user-attachments/assets/e9ef6cd7-e6fd-4c25-898b-0dde592bbfae">

2024-12-04 22:32 UTC, nshoes commented
@joshk made adjustments to the `show` and `new` views:

#### show

<img width="1210" alt="CleanShot 2024-12-04 at 14 31 26@2x" src="https://github.com/user-attachments/assets/927e2f30-8b65-439d-8bb9-418fdbf6969a">

#### new

<img width="1276" alt="CleanShot 2024-12-04 at 14 31 48@2x" src="https://github.com/user-attachments/assets/e37c999d-0167-45be-b363-e1ef1c7641fd">

2024-12-04 22:37 UTC, joshk commented on lib/nerves_hub/devices.ex
> +        # Deployments.set_deployment(updated)
When a device connects it looks for a deployment (if it doesn't have one). So when moving a device from one product to another, clearing the deployment and disconnecting the device would also take care of assigns and data the device should refresh. eg. we send signing keys to the device on connect, so this would make sure the device would be resent the correct signing keys.

2024-12-04 22:38 UTC, joshk commented on lib/nerves_hub/devices/device.ex
> +    field(:deployment_conflict, Ecto.Enum,
Ok, seems fair. Do we show this information anywhere right now?

2024-12-04 22:39 UTC, joshk commented
Love the UI changes.

For the `show` page, could we move the matching conditions to below the `Deployment details` section?

2024-12-04 22:43 UTC, nshoes commented
Done!

2024-12-04 22:51 UTC, joshk commented
@nshoes can you resolve the PR merge conflicts and then we can merge this in!

2024-12-04 22:55 UTC, nshoes commented on lib/nerves_hub/devices.ex
> +        # Deployments.set_deployment(updated)
Got it, that makes sense!

2024-12-04 22:56 UTC, nshoes commented on lib/nerves_hub/devices/device.ex
> +    field(:deployment_conflict, Ecto.Enum,
We do not; but since it's added in here, we should. I'll implement.

2024-12-05 16:36 UTC, nshoes commented on lib/nerves_hub/devices/device.ex
> +    field(:deployment_conflict, Ecto.Enum,
I think this info may need a bigger callout, but I think this is fine for now:
<img width="1229" alt="CleanShot 2024-12-05 at 08 34 57@2x" src="https://github.com/user-attachments/assets/f8d1f450-07eb-4985-9eaf-b66be26ddd11">

2024-12-05 20:06 UTC, nshoes commented on lib/nerves_hub/devices/device.ex
> +    field(:deployment_conflict, Ecto.Enum,
I think an audit message makes more sense here :) Good callout.

2024-12-05 20:14 UTC, nshoes commented on lib/nerves_hub/devices/device.ex
> +    field(:deployment_conflict, Ecto.Enum,
Fixed, let me know if you have feedback on [the audit description](https://github.com/nerves-hub/nerves_hub_web/pull/1652/commits/21ec1f9044aa1c2f060e246c12dac8f9cb0d1fd7#diff-48cec1d45c7f0dac953ea8a89cecbf1c568e6a9b61b02a863a3ac4c23fb68920R337).

2024-12-05 20:57 UTC, nshoes commented on lib/nerves_hub/devices/device.ex
> +    field(:deployment_conflict, Ecto.Enum,
More changes from our conversations on Slack: https://github.com/nerves-hub/nerves_hub_web/pull/1652/commits/7258ca6d4db16f9cd53b0ff00deecb604efa5916

2024-12-06 22:47 UTC, joshk approved these changes
Amazing work!

This change turned out to be bigger than we thought, and you rocked it!

2024-12-06 22:55 UTC, merged