Replace Scrivener with Flop
nerves-hub/nerves_hub_web pull request #1656
Opened 2024-11-21 15:22 UTC by lawik

This is pretty much a bug-by-bug compatible implementation as far as I can tell.

2024-11-21 15:24 UTC, lawik commented
Takes care of issue #1656 

Flop wants the struct so it is a bit messy. There is a lot of potential tidying up that one could do. But this just rips out the old and provides identical functionality.

2024-11-21 15:47 UTC, nshoes requested changes
Thank you so much for doing this! Couple issues I found:

#### Cannot get back to page 1 after navigating to other pages
The double carets or clicking `1` doesn't send you back to the first page.

![CleanShot 2024-11-21 at 07 43 28](https://github.com/user-attachments/assets/f735097b-ce6a-4416-912d-4e0b2758f872)

#### Single page shows two page `1` icons
They both link to page 1, but it's confusing and should only display a single tile.
<img width="423" alt="CleanShot 2024-11-21 at 07 46 05@2x" src="https://github.com/user-attachments/assets/3db36541-8a1f-453b-93b6-86cf5f7dacde">

2024-11-21 15:47 UTC, nshoes commented on lib/nerves_hub/devices.ex
> +    flop = %Flop{page: pagination[:page] || 1, page_size: pagination[:page_size] || 10}
```suggestion
    pagination = Map.get(opts, :pagination, %{page: 1, page_size: 10})
    sorting = Map.get(opts, :sort, {:asc, :identifier})
    filters = Map.get(opts, :filters, %{})

    flop = %Flop{page: pagination[:page], page_size: pagination[:page_size]}
```

2024-11-21 15:47 UTC, nshoes commented on lib/nerves_hub/devices.ex
> +    flop = %Flop{page: pagination.page, page_size: pagination.page_size}
Do we care that these could be `nil` here? We could adopt my suggestion from above if so.

2024-11-21 15:47 UTC, nshoes commented on lib/nerves_hub/devices.ex
> +    {entries, _pager} = get_devices_by_org_id_and_product_id_with_pager(org_id, product_id, opts)
I was originally off-put by `pager`, but its definition is "one who pages"... I love it 😆

2024-11-21 15:47 UTC, nshoes commented on lib/nerves_hub_web/views/layout_view.ex
> +          to: "?page=#{@page_number - 1}#{@anchor}",
Are we resolving an index starting at 1 vs 0 here? Is Flop zero-based?

2024-11-21 15:49 UTC, nshoes commented
> But this just rips out the old and provides identical functionality.

I didn't see this before making my review, this makes me think that the bugs I listed already existed, but I'd love to take care of them here.

2024-11-22 10:14 UTC, lawik commented
@nshoes no worries, it is indeed bug-for-bug-compatible. I hope to take some time next week and make it not terrible. But I think replacing the dep is a good starting point and then improve from there.

2024-11-22 10:15 UTC, lawik commented on lib/nerves_hub_web/views/layout_view.ex
> +          to: "?page=#{@page_number - 1}#{@anchor}",
Offset/Limit mode is zero-based, page-mode is not. Fairly certain :)

2024-11-22 10:16 UTC, lawik commented on lib/nerves_hub/devices.ex
> +    {entries, _pager} = get_devices_by_org_id_and_product_id_with_pager(org_id, product_id, opts)
I didn't even think very hard. But of course intended this very fitting name :P

2024-11-22 10:16 UTC, lawik commented on lib/nerves_hub/devices.ex
> +    flop = %Flop{page: pagination.page, page_size: pagination.page_size}
They are only used in one place and will never be nil so I don't think we care.

2024-11-22 21:06 UTC, nshoes approved these changes

2024-11-22 21:06 UTC, merged