Add script section to device UI
nerves-hub/nerves_hub_web pull request #1689
Opened 2024-12-09 12:30 UTC by elinol

Solves #1681 

Adds a simple section on device page for listing and running support scripts.

Not too much time spent on the looks since the whole UI is redesigned.

2024-12-09 12:43 UTC, elinol commented on test/nerves_hub_web/live/devices/show_test.exs
> +    end
I wanted to add a test for clicking Run button, but it seems too involved with device channel and such. Couldn't find any tests for running tests at all, might be better to start there?

2024-12-09 12:50 UTC, elinol commented
![image](https://github.com/user-attachments/assets/935f9173-f22e-4ec6-86e5-40e12eeb196d)

2024-12-09 19:38 UTC, nshoes commented on lib/nerves_hub_web/live/devices/show.ex
> +    |> assign(:script_output, %{output: output, id: script_id})
This means we can only see a single script's output at a time. If we care about seeing multiple, we could leverage the `order_by(:name)` from `Scripts.all_by_product/1` and build a data structure that's easier to depend on. What are your thoughts?

2024-12-09 20:45 UTC, joshk requested changes
I really love the direction of this. This is a great first implementation.

Similar to how the API allows you to do run support scripts, you will need to check if the user has the required role (https://github.com/nerves-hub/nerves_hub_web/blob/main/lib/nerves_hub_web/controllers/api/script_controller.ex#L36)

In our liveviews we do this with: `authorized!(:"support_scripts:run", socket.assigns.org_user)` and then adding the definition to https://github.com/nerves-hub/nerves_hub_web/blob/d7215609eb3c8c5584168d0324bb0d0efa5a269d/lib/nerves_hub_web/helpers/authorization.ex#L5

2024-12-09 20:45 UTC, joshk commented on lib/nerves_hub_web/live/devices/show.ex
> +    |> assign(:script_output, %{output: output, id: script_id})
there is also another way to do this, instead of using an `assign`, you can use `push_event` and have a js function which updates the UI. This means that you can run two scripts and the second script run won't remove the result from the first script run. I would recommend `push_event` over `assign`

2024-12-09 20:45 UTC, joshk commented on lib/nerves_hub_web/live/devices/show.ex
> +    output = Scripts.Runner.send(device, script)
I believe this is a blocking function, which means it would block the LiveView from doing anything while its processing. I think you could use https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#start_async/4 to run the command, and then display a flash to say that the script is running.

Then in `def handle_async(:run_script, {:ok, result}, socket) do` you can update the flash and use `push_event` to update the UI.

2024-12-09 20:45 UTC, joshk commented on lib/nerves_hub_web/live/devices/show.ex
> +    output = Scripts.Runner.send(device, script)
With this change you could also remove lines 24, 50, and 51.

2024-12-10 08:12 UTC, elinol commented on lib/nerves_hub_web/live/devices/show.ex
> +    |> assign(:script_output, %{output: output, id: script_id})
@joshk I'm not that found of involving js stuff but I'll give this a go and who knows, I might be convinced otherwise

2024-12-10 08:16 UTC, elinol commented on lib/nerves_hub_web/live/devices/show.ex
> +    |> assign(:script_output, %{output: output, id: script_id})
oh, do you mean like `JS.hide()` or so? I'm ok with that :D

2024-12-10 15:29 UTC, elinol commented
![image](https://github.com/user-attachments/assets/4188d8a2-c14c-4ad5-beb3-e6cbc18db152)

2024-12-10 15:33 UTC, elinol commented on lib/nerves_hub_web/live/devices/show.ex
> +    |> assign(:script_output, %{output: output, id: script_id})
Why exactly do you recommend `push_event` over assigns @joshk ?

I found it simpler to use the assigns together with `start_async`

2024-12-10 21:52 UTC, joshk requested changes
One tiny change requested, then we can merge!

2024-12-10 21:52 UTC, joshk commented on lib/nerves_hub_web/helpers/authorization.ex
> +  def authorized?(:"support_script:run", %OrgUser{role: role}), do: role_check(:manage, role)
Looking at the permissions required for `API.ScriptController.send`, you can use `:view` for `role_check`

2024-12-10 21:52 UTC, joshk commented on test/nerves_hub_web/live/devices/show_test.exs
> +    end
Agree, this is fine for now.

2024-12-10 21:56 UTC, joshk commented on lib/nerves_hub_web/live/devices/show.ex
> +    |> assign(:script_output, %{output: output, id: script_id})
I think your approach is fine for shipping.

2024-12-10 22:02 UTC, elinol commented on lib/nerves_hub_web/helpers/authorization.ex
> +  def authorized?(:"support_script:run", %OrgUser{role: role}), do: role_check(:manage, role)
oops missed that. fixed now!

2024-12-10 22:05 UTC, joshk approved these changes

2024-12-10 22:12 UTC, merged