Ignore empty metrics map
nerves-hub/nerves_hub_web pull request #1694
Opened 2024-12-11 13:45 UTC by elinol

Solves #1662.

Also, the deprecated broadcast topic for health checks is replaced with correct one.

2024-12-11 23:55 UTC, joshk requested changes

2024-12-11 23:55 UTC, joshk commented on lib/nerves_hub_web/live/devices/show.ex
> +    NervesHubWeb.DeviceEndpoint.broadcast(topic, "health:check", %{})
Why did you change these lines?

We need to use `socket.endpoint.broadcast` as the web app will fail if `DeviceEndpoint` isn't started (it isn't started in production, they are only started for there respective apps)

2024-12-12 08:24 UTC, elinol commented on lib/nerves_hub_web/live/devices/show.ex
> +    NervesHubWeb.DeviceEndpoint.broadcast(topic, "health:check", %{})
It had to be changed to include "extensions", and I just copied how it was done in other files in the app. Is it wise to change to `socket.endpoint.broadcast` in all those files then?

2024-12-12 08:34 UTC, joshk commented on lib/nerves_hub_web/live/devices/show.ex
> +    NervesHubWeb.DeviceEndpoint.broadcast(topic, "health:check", %{})
oh, which other files does this exist?

2024-12-12 08:41 UTC, elinol commented on lib/nerves_hub_web/live/devices/show.ex
> +    NervesHubWeb.DeviceEndpoint.broadcast(topic, "health:check", %{})
In `NervesHub.Devices`, `NervesHub.Products`, `NervesHub.Extensions.Health` etc. In fact it seems like `DeviceEndpoint` is used all over

2024-12-12 08:59 UTC, joshk commented on lib/nerves_hub_web/live/devices/show.ex
> +    NervesHubWeb.DeviceEndpoint.broadcast(topic, "health:check", %{})
It looks like `NervesHubWeb.DeviceEndpoint` was added several times when the extensions work was completed. This has the chance of failing. Changing these in context modules is tricky, as we don't have a socket to use, but I also see some that can be removed. I think these extra ones found will need to be a different PR. If you can update your PR then we can merge it in.

2024-12-12 09:13 UTC, elinol commented on lib/nerves_hub_web/live/devices/show.ex
> +    NervesHubWeb.DeviceEndpoint.broadcast(topic, "health:check", %{})
Cool, I'll try that as soon I get my little device to connect

2024-12-12 10:09 UTC, elinol commented on lib/nerves_hub_web/live/devices/show.ex
> +    NervesHubWeb.DeviceEndpoint.broadcast(topic, "health:check", %{})
PubSub didn't work, it doesn't reach the device. what about `socket.endpoint.broadcast(topic, "health:check", %{})`? Or it that equal to `NervesHubWeb.DeviceEndpoint.broadcast(topic, "health:check", %{})` ?

2024-12-12 21:22 UTC, joshk commented on lib/nerves_hub_web/live/devices/show.ex
> +    NervesHubWeb.DeviceEndpoint.broadcast(topic, "health:check", %{})
Using `socket.endpoint.broadcast(topic, "health:check", %{})` is fine within LiveView controllers, but it won't work in Contexts (eg. `NervesHub.Devices` because we would need to pass the socket in.

For `broadcasts` within Contexts we should use `NervesHub.PubSub.broadcast`, if we can. It would look something like `NervesHub.PubSub.broadcast(NervesHub.PubSub, topic, event, message)`. Happy to pair on this next week.

2024-12-13 08:36 UTC, elinol commented on lib/nerves_hub_web/live/devices/show.ex
> +    NervesHubWeb.DeviceEndpoint.broadcast(topic, "health:check", %{})
Yes, let's!

2024-12-17 00:51 UTC, joshk approved these changes

2024-12-17 00:51 UTC, merged