Bulk move devices to deployment
nerves-hub/nerves_hub_web pull request #1718
Opened 2024-12-27 16:23 UTC by nshoes

This is a quality-of-life improvement since we're moving away from devices automatically finding deployments.

### Todos
- [ ] Tests

2024-12-31 00:41 UTC, joshk requested changes
As discussed with Nate on a Zoom, we need to check if the device(s) meet the requirements of the Deployment before we assign it to them

2025-01-02 19:55 UTC, nshoes commented
With info flash:

![CleanShot 2025-01-02 at 11 54 24](https://github.com/user-attachments/assets/bfaf12a4-acdd-48a8-9705-968c2dbf70de)

2025-01-03 21:09 UTC, joshk requested changes
Really awesome, some minor suggested changes.

2025-01-03 21:09 UTC, joshk commented on lib/nerves_hub/devices.ex
> +  @spec move_many_to_deployment([integer()], integer()) :: {integer(), nil}
I think it would be good to change the return values to be specific to the task and not Ecto. eg.
`{:ok, {updated: 5, ignored: 0}}`?

2025-01-03 21:09 UTC, joshk commented on lib/nerves_hub/devices.ex
> +      |> Repo.one()
My brain is having trouble reading this. Are you fetching the Firmware attached to the Deployment? I think it would read better to fetch the deployment and preload the firmware. We can also move that method to the `Deployments` context (there should we one we can use there)

2025-01-03 21:09 UTC, joshk commented on lib/nerves_hub_web/live/devices/index.ex
> +      end)
Could you move this to its own method? eg. `update_flash(socket, devices_updated_count, devices_not_updated_count)`

2025-01-06 15:22 UTC, nshoes commented on lib/nerves_hub/devices.ex
> +  @spec move_many_to_deployment([integer()], integer()) :: {integer(), nil}
I swapped back and forth between what I have now and that, will gladly change.

2025-01-06 15:22 UTC, nshoes commented on lib/nerves_hub/devices.ex
> +      |> Repo.one()
I wanted to get the firmware from just the deployment ID. I can see how this could be confusing, I'll change.

2025-01-06 15:50 UTC, nshoes commented on lib/nerves_hub_web/live/devices/index.ex
> +      end)
https://github.com/nerves-hub/nerves_hub_web/pull/1718/commits/eb7ff2424ac9cc638ca804d8e2be0bdcef5d8d8c

2025-01-06 20:33 UTC, joshk approved these changes
Looking great. One small comment regarding some dead code.

2025-01-06 20:33 UTC, joshk commented on lib/nerves_hub/devices.ex
> +    |> Repo.one()
Did you mean to leave this here?

2025-01-06 22:12 UTC, nshoes commented on lib/nerves_hub/devices.ex
> +    |> Repo.one()
Nope! Removed, thank you.

2025-01-06 22:25 UTC, merged